### ISSUE TITLE
大佬，R5 4600U的小新pro13能使用吗

### ISSUE THREAD

**Issue by awasl** [APU-Hackintosh/Lenovo-Xiaoxin-Pro13-AMD-hackintosh#1]

**Comment by AngelaCooljx** [comment]
可以 ![71995D7206EF478BF1989BBF4FBCA5ED1685854070136](https://github.com/APU-Hackintosh/Lenovo-Xiaoxin-Pro13-AMD-hackintosh/assets/49330826/c21338d1-751f-4598-a123-a0bafbc42bbf)

**Comment by awasl** [comment]
好的好的，谢谢大佬

**Comment by awasl** [comment]
大佬，那这个b808是改成什么呢

**Comment by AngelaCooljx** [comment]
b806，其实改不改都无所谓，完全没影响，只要改对应macos版本(12.x, 13.0 to 13.2.1)的那一个patch的第三四位，只有那一行有效，具体看 https://github.com/AMD-OSX/AMD_Vanilla

**Comment by awasl** [comment]
好的好的

**Comment by AngelaCooljx** [comment]
主要还是看机型的，不只是看U，但可以先直接用，有问题再慢慢改，毕竟我这个也是直接改的Yoga16s的

**Comment by AngelaCooljx** [comment]
自用12.6.7，11可以尝试，13还不支持

**Comment by app318** [comment]
大佬，可否帮修改一份R5 4600U的小新pro13的EFI文件，不会改，谢谢啦！
