### ISSUE TITLE
安装成功，卡顿，小机率无法识别触控板

### ISSUE THREAD

**Issue by dashuai09** [APU-Hackintosh/Lenovo-Xiaoxin-Pro13-AMD-hackintosh#2]
网卡更换了AX210，直接安装成功；WIFI正常，蓝牙无法打开；
系统卡顿明显，不满足日常使用，鼠标经常性彩虹点；
小机率无法识别触控板，重启恢复。

ventura不能正常安装

期待进度99.9%

**Comment by dashuai09** [comment]
大佬，BIOS除了关闭安全启动，还需别的设置吗？
现在太卡了，鼠标点一下，反应1s，点五下，有一下要反应5s；不知道有没有什么排障方法呢？
十分感谢 🙇‍谢谢谢谢

**Comment by AngelaCooljx** [comment]
是登录了 iCloud 吗，尝试禁用 NootedRed 以后进系统退出登录 iCloud，再开启 NootedRed 试试
