### ISSUE TITLE
使用磁盘工具抹除硬盘时死机

### ISSUE THREAD

**Issue by Watish** [APU-Hackintosh/Lenovo-Xiaoxin-Pro13-AMD-hackintosh#3]
我的电脑是联想小新Air14 ARE 2020，根据[zabdottler](https://github.com/zabdottler)
/
[Lenovo-Yoga-16S-hackintosh](https://github.com/zabdottler/Lenovo-Yoga-16S-hackintosh)仓库的指导，关闭了一个xhci，成功进入了安装界面，但是每次在抹除硬盘时死机，我的硬盘型号是SAMSUNG MZVLB512HBJQ-000L2
这种情况在其它不同的小新型号上似乎同样存在

**Comment by AngelaCooljx** [comment]
https://www.v2ex.com/t/906360 pm981a硬盘问题，只有更换硬盘或者做好屏蔽后安装到外置硬盘解决
