### ISSUE TITLE
同款机器，卡在第一次进系统LOGO，主板修改啥设置吗？开-v报错如图。

### ISSUE THREAD

**Issue by losenli** [APU-Hackintosh/Lenovo-Xiaoxin-Pro13-AMD-hackintosh#5]
![dfd8f86e92b6b24cb6f58d40a0ff912](https://github.com/APU-Hackintosh/Lenovo-Xiaoxin-Pro13-AMD-hackintosh/assets/32837355/338ebd09-b5de-49b3-970e-8bedb3eee5df)

**Comment by losenli** [comment]
![be3e4475bacc85e44f2db6156fc95e5](https://github.com/APU-Hackintosh/Lenovo-Xiaoxin-Pro13-AMD-hackintosh/assets/32837355/1dfcff9f-a592-4362-a956-5a12dbfa2130)

**Comment by losenli** [comment]
可以了·，，但是风扇特别吵。。

**Comment by AngelaCooljx** [comment]
刚开机会有程序后台高占用，可以静置等一段时间观察功耗是否降到7W左右，温度50度以内

**Comment by losenli** [comment]
> 刚开机会有程序后台高占用，可以静置等一段时间观察功耗是否降到7W左右，温度50度以内

长时间用的稳定不，老哥。

**Comment by AngelaCooljx** [comment]
NootedRed 还处于尝鲜阶段，视频图像硬件编解码还有问题

**Comment by losenli** [comment]
> NootedRed 还处于尝鲜阶段，视频图像硬件编解码还有问题

谢谢，那我就挂外置硬盘盒玩玩吧。
