### ISSUE TITLE
4800h 拯救者 使用此efi，引导不到安装页面

### ISSUE THREAD

**Issue by sevenblack3166** [APU-Hackintosh/Lenovo-Xiaoxin-Pro13-AMD-hackintosh#7]
![IMG_6095](https://github.com/APU-Hackintosh/Lenovo-Xiaoxin-Pro13-AMD-hackintosh/assets/131241752/7211328a-bfa9-40c6-a589-a30827d59fcc)

配置 4800h 1650 西数sn730 海力士内存

**Comment by AngelaCooljx** [comment]
机型不适用
