### ISSUE TITLE
*s In Nemory Panic Stackshot Succeeded os Bytes Traced 13342 (Uncompressed 39264)**

### ISSUE THREAD

**Issue by qgyhm** [APU-Hackintosh/Lenovo-Xiaoxin-Pro13-AMD-hackintosh#9]
![mmexport1686417080481](https://github.com/APU-Hackintosh/Lenovo-Xiaoxin-Pro13-AMD-hackintosh/assets/68739004/397a4846-5291-4c95-83b6-88f465384367)
一直卡这里，小新15air2020

**Comment by AngelaCooljx** [comment]
尝试禁用nootedred安装，另外非本机型可能存在其他问题。
